### PR TITLE
site normalization fixes

### LINKED ISSUE #171: site(d) <- results in corrupt profiles
For some reason the NEON data once converted into an SPC does not play nicely with:
```r
subset(S, siteID %in% c('SJER', 'SOAP', 'TEAK'))
```
There is a lot of "magic" involved with getting the NEON data into R, resulting in a global environment full of objects. Also, the final object `S` contains many duplicated columns resulting from joins.

This has nothing to do with `aqp::subset`, rather novel input data and `site(x) <-`.

Setup:
```r
# Load required packages
library(neonUtilities)
library(aqp)
library(dplyr)

## ----download-data, results='hide'--------------------------------------------------------------------

MP <- loadByProduct(dpID = "DP1.00096.001", check.size = F)

# Unlist to environment - see download/explore tutorial for description
list2env(MP, .GlobalEnv)



## ----join-bgc-----------------------------------------------------------------------------------------

# duplicate the 'horizon' information into a new table
S <- mgp_perhorizon

# duplicate the biogeochemical information into a new table
B <- mgp_perbiogeosample

# Select only 'Regular' samples (not audit)
B <- B[B$biogeoSampleType=="Regular" & 
         !is.na(B$biogeoSampleType),]

# Join biogeochem data to horizon data
S <- left_join(S, B, by=c('horizonID', 'siteID',
                          'pitID','setDate',
                          'collectDate',
                          'domainID',
                          'horizonName'))
S <- arrange(S, siteID, horizonTopDepth)



## ----site-labels--------------------------------------------------------------------------------------

## combine 'domainID' and 'siteID' into a new label variable
S$siteLabel=paste(S$domainID, S$siteID, sep="-")


# init SPC
depths(S) <- siteLabel ~ horizonTopDepth + horizonBottomDepth
```

Corrupt SPC here:
```r
# move site-level attributes to @site
site(S) <- ~ siteID + pitNamedLocation.x + pitID + labProjID + laboratoryName + nrcsDescriptionID
```

View error here:
```
S[42, ]
```

### PR DESCRIPTION
**Pull request by brownag**
Closes #171 (which still needs a working example, see #172), also uses `data.table` .SD style syntax to replace iteration by `ddply` #157.

Adds a new warning if you specify a problematic formula to `site<-` -- i.e. one that does not produce a result that is 1:1 with the existing site table / profile ID / `profile_id()`-- leaving data unchanged. 

This is hopefully OK and sufficient to explain to users who might have expected the horizon var to move to site.

Also, I believe it adds 7 tests which should put us... over 1000!

### CODE REVIEW

File: R/SoilProfileCollection-setters.R [hunk 1]
```diff
@@ -335,22 +335,26 @@ setReplaceMethod("site", signature(object = "SoilProfileCollection"),
...
-      .fun=function(x) {
-	      unique(x[, names_attr, drop = FALSE])
-      }
-  )
-
+  .SD <- NULL
+  
+  dth <- as.data.table(horizons(object))
+  
+  new_site_data <- .as.data.frame.aqp(unique(dth[, .SD, .SDcols = names_attr]), aqp_df_class(object))
```
Comment (dylanbeaudette) [inline R/SoilProfileCollection-setters.R:349]: nice, this helps me understand what `.SD` is all about.

Also, note to myself: I'll need to follow-up with using `.as.data.frame.aqp` in all of my recently converted code that operates on SPCs.

**Review by dylanbeaudette — APPROVED** [review]
